/*
 * qualinsight-plugins-sonarqube-badges
 * Copyright (c) 2015-2016, QualInsight
 * http://www.qualinsight.com/
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program. If not, you can retrieve a copy
 * from <http://www.gnu.org/licenses/>.
 */
package com.qualinsight.plugins.sonarqube.badges.ws;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.font.FontRenderContext;
import java.awt.geom.AffineTransform;
import org.apache.batik.dom.GenericDOMImplementation;
import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.svggen.SVGGraphics2D;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sonar.api.server.ServerSide;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import com.qualinsight.plugins.sonarqube.badges.font.FontManager;

/**
 * Generates SVG images.
 *
 * @author Michel Pawlak
 */
@ServerSide
public final class SVGImageGenerator {

    private static final Logger LOGGER = LoggerFactory.getLogger(SVGImageGenerator.class);

    private static final String SVG_NAMESPACE_URI = "http://www.w3.org/2000/svg";

    private static final String QUALIFIED_NAME = "svg";

    private static final String COMMENT_STRING = "Generated by QualInsight SVG Badge Generator";

    private static final int X_MARGIN = 4;

    private static final int CANVAS_HEIGHT = 20;

    private static final int BACKGROUND_CORNER_ARC_DIAMETER = 6;

    private static final Color COLOR_BACKGROUND_LABEL = new Color(85, 85, 85, 255);

    private static final Color COLOR_SHADOW = new Color(0, 0, 0, 85);

    private static final Color COLOR_TEXT = new Color(255, 255, 255, 255);

    private static final int Y_OFFSET_SHADOW = 15;

    private static final int Y_OFFSET_TEXT = 14;

    private static final FontRenderContext FONT_RENDER_CONTEXT = new FontRenderContext(new AffineTransform(), true, true);

    private SVGGeneratorContext svgGeneratorContext;

    private FontManager fontManager;

    /**
     * Container holding data required in order to generate SVG images.
     *
     * @author Michel Pawlak
     */
    public static class Data {

        private String labelText;

        private String contentText;

        private Color contentBackgroundColor;

        private Data() {
        }

        /**
         * Sets the text of the label part of a SVG badge.
         *
         * @param labelText badge's label text
         * @return data container
         */
        public Data withLabelText(final String labelText) {
            this.labelText = labelText;
            return this;
        }

        /**
         * Sets the text of the content part of a SVG badge.
         *
         * @param contentText badge's content text
         * @return data container
         */
        public Data withContentText(final String contentText) {
            this.contentText = contentText;
            return this;
        }

        /**
         * Sets the background color to be used for the content part of the SVG badge.
         *
         * @param contentBackgroundColor background color to be used
         * @return data container
         */
        public Data withContentBackgroundColor(final Color contentBackgroundColor) {
            this.contentBackgroundColor = contentBackgroundColor;
            return this;
        }

        /**
         * Instantiates a new Data container.
         *
         * @return empty data container
         */
        public static Data create() {
            return new Data();
        }

        /**
         * Content text getter.
         *
         * @return content text
         */
        public String contentText() {
            return this.contentText;
        }

        /**
         * Label text getter.
         *
         * @return label text
         */
        public String labelText() {
            return this.labelText;
        }

        /**
         * Content background color getter.
         *
         * @return content background color.
         */
        public Color contentBackgroundColor() {
            return this.contentBackgroundColor;
        }

    }

    /**
     * {@link SVGImageGenerator} IoC constructor.
     *
     * @param fontManager FontManager that will be used to retrieve Fonts used for badges generation
     */
    public SVGImageGenerator(final FontManager fontManager) {
        this.fontManager = fontManager;
        final DOMImplementation domImplementation = GenericDOMImplementation.getDOMImplementation();
        final Document document = domImplementation.createDocument(SVG_NAMESPACE_URI, QUALIFIED_NAME, null);
        this.svgGeneratorContext = SVGGeneratorContext.createDefault(document);
        this.svgGeneratorContext.setComment(COMMENT_STRING);
        LOGGER.info("SVGImageGenerator is now ready.");
    }

    /**
     * Generates a SVGGraphics2D object from a provided Data object.
     *
     * @param data Data object holding data required to produce a SVGGraphics2D object
     * @return generated SVGGraphics2D object
     */
    public SVGGraphics2D generateFor(final Data data) {
        final int labelWidth = computeWidth(data.labelText());
        final int contentWidth = computeWidth(data.contentText());
        // new SVG graphics
        final SVGGraphics2D svgGraphics2D = new SVGGraphics2D(this.svgGeneratorContext, false);
        // set SVG canvas size
        svgGraphics2D.setSVGCanvasSize(new Dimension(labelWidth + contentWidth + (4 * X_MARGIN), CANVAS_HEIGHT));
        // set font
        svgGraphics2D.setFont(FontManager.DUMMY_FONT);
        // draw Label background
        svgGraphics2D.setColor(COLOR_BACKGROUND_LABEL);
        svgGraphics2D.fillRoundRect(0, 0, labelWidth + (2 * X_MARGIN), CANVAS_HEIGHT, BACKGROUND_CORNER_ARC_DIAMETER, BACKGROUND_CORNER_ARC_DIAMETER);
        svgGraphics2D.fillRect(BACKGROUND_CORNER_ARC_DIAMETER, 0, (labelWidth + (2 * X_MARGIN)) - BACKGROUND_CORNER_ARC_DIAMETER, CANVAS_HEIGHT);
        // draw Label text shadow
        svgGraphics2D.setColor(COLOR_SHADOW);
        svgGraphics2D.drawString(data.labelText(), X_MARGIN, Y_OFFSET_SHADOW);
        // draw Label text
        svgGraphics2D.setColor(COLOR_TEXT);
        svgGraphics2D.drawString(data.labelText(), X_MARGIN, Y_OFFSET_TEXT);
        // draw result background
        svgGraphics2D.setColor(data.contentBackgroundColor());
        svgGraphics2D.fillRoundRect(labelWidth + (2 * X_MARGIN), 0, contentWidth + (2 * X_MARGIN), CANVAS_HEIGHT, BACKGROUND_CORNER_ARC_DIAMETER, BACKGROUND_CORNER_ARC_DIAMETER);
        svgGraphics2D.fillRect(labelWidth + (2 * X_MARGIN), 0, (contentWidth + (2 * X_MARGIN)) - BACKGROUND_CORNER_ARC_DIAMETER, CANVAS_HEIGHT);
        // draw result text shadow
        svgGraphics2D.setColor(COLOR_SHADOW);
        svgGraphics2D.drawString(data.contentText(), labelWidth + (3 * X_MARGIN), Y_OFFSET_SHADOW);
        // draw result text
        svgGraphics2D.setColor(COLOR_TEXT);
        svgGraphics2D.drawString(data.contentText(), labelWidth + (3 * X_MARGIN), Y_OFFSET_TEXT);
        return svgGraphics2D;
    }

    private int computeWidth(final String text) {
        return (int) (this.fontManager.preferredFont()
            .getStringBounds(text, SVGImageGenerator.FONT_RENDER_CONTEXT).getWidth());
    }

    /**
     * Provides the FontManager object that needs to be used to retrieve Fonts.
     *
     * @return Registered FontManager
     */
    public FontManager fontManager() {
        return this.fontManager;
    }

}
